version: "3"

services:
  backend:
    build: ./backend
    container_name: todolist-backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - PORT=3002
    depends_on:
      - mongo
    mem_limit: 200m
    memswap_limit: 250m

  mongo:
    container_name: todolist-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    mem_limit: 128m
    memswap_limit: 150m

  frontend:
    container_name: todolist-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    mem_limit: 120m
    memswap_limit: 150m
