name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > aws_rsa.pem
          chmod 600 aws_rsa.pem

      - name: Debug private key
        run: |
          cat aws_rsa.pem | head -n 5
          ls -l aws_rsa.pem

      - name: Deploy to server
        run: |
          scp -i aws_rsa.pem -v -o StrictHostKeyChecking=yes -r ./ ubuntu@$AWS_LS_IP:/home/ubuntu/todolist

          ssh -i aws_rsa.pem -v -o StrictHostKeyChecking=yes ubuntu@$AWS_LS_IP << 'EOF'
            cd /home/ubuntu/todolist
            docker-compose down
            docker-compose up -d
          EOF

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_LS_IP: ${{ secrets.AWS_LS_IP }}
